# Generated by Django 6.1.1 on 2026-09-27 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Vechta Wheat Field A', max_length=200)),
                ('crop_type', models.CharField(max_length=100)),
                ('boundary_coordinates', models.JSONField(help_text='Stores GeoJSON polygon geometry defining the exact field boundaries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StressAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(auto_now_add=True)),
                ('stress_clusters', models.JSONField(help_text='Stores the bounding box coordinates of stressed 10x10m pixel clusters generated by the AI.')),
                ('overall_ndvi', models.FloatField(blank=True, help_text='Average NDVI calculated for the entire field during this scan.', null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='monitor.agriculturalfield')),
            ],
        ),
    ]
