from django.db import models

class AgriculturalField(models.Model):
    name = models.CharField(max_length=200, help_text="e.g., Vechta Wheat Field A")
    crop_type = models.CharField(max_length=100)
    boundary_coordinates = models.JSONField(
        help_text="Stores GeoJSON polygon geometry defining the exact field boundaries."
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.crop_type})"


class StressAnomaly(models.Model):
    field = models.ForeignKey(AgriculturalField, on_delete=models.CASCADE, related_name='anomalies')
    scan_date = models.DateField(auto_now_add=True)
    stress_clusters = models.JSONField(
        help_text="Stores the bounding box coordinates of stressed 10x10m pixel clusters generated by the AI."
    )
    overall_ndvi = models.FloatField(
        null=True, 
        blank=True, 
        help_text="Average NDVI calculated for the entire field during this scan."
    )

    def __str__(self):
        return f"Anomaly flagged in {self.field.name} on {self.scan_date}"